server:
  port: 8768
spring:  jpa:    properties:      hibernate:
        show_sql:true
        format_sql:true    show-sql: true
      h2:    console:      enabled: true      path: /h2  datasource:    url: jdbc:h2:mem:testdb    driver-class-name: org.h2.Driver
    username: sa  application:    name: STOCK-PRICE

    